//
// This file has been automatically generated by makeVCXProj.py
//
// Do not change this file manually, instead reconfigure OGDF!

#define USE_COIN
#define COIN_OSI_CLP
#define OGDF_DLL

#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0502
#endif
